version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db_name
    ports:
      - "5432:5432"
    volumes:
      - db_data:your_db_path

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
    ports:
      - "8080:8080"

volumes:
  db_data:
